echo "This is pyhton file"
echo "This is second commit to file"
echo "This is third commit to file"
echo "Example of pull request from dev to stage branch"
echo "This is 4th commit"
echo "Example for cherry-pick from main branch"
echo "Adding this 1st line to perform rebase"
